- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderCreateResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
- src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderSevice.java
- src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
- src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
- src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductService.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
- src/main/java/com/sparta/levelup_backend/domain/user/userservice/UserService.java
- src/main/java/com/sparta/levelup_backend/domain/user/userservice/UserServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/GlobalExceptionHandler.java
- src/main/java/com/sparta/levelup_backend/exception/common/BusinessException.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- src/main/java/com/sparta/levelup_backend/exception/common/NotFoundException.java
- src/main/java/com/sparta/levelup_backend/exception/common/ProductOutOfAmount.java
> feat : orderCreate

- src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
- src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
- src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductService.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductmakedataService.java
- src/main/java/com/sparta/levelup_backend/domain/user/entity/UserEntity.java
product service merge 오류로 생긴 코드 증발 해결
> feat: Create ProductService implementation

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/OrderValidationMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
> feat : orderRead

- src/main/java/com/sparta/levelup_backend/common/ApiResponse.java
>  fix : ApiRes

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/OrderValidationMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/requestDto/OrderCreateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/dto/responseDto/OrderResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
> fix : Order read

- src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
> fix : oderUser

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
>  feat : orderComplete

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderController.java
- src/main/java/com/sparta/levelup_backend/domain/order/entity/OrderEntity.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderService.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
결제 요청 상태 일 때 주문 취소
거래중 상태 일 때  주문 취소 (판매자만 가능)
> feat : Order delete

- src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
- src/main/java/com/sparta/levelup_backend/config/CustomUserDetails.java
- src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductCreateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/requestDto/ProductUpdateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductCreateResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductDeleteResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductUpdateResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/entity/ProductEntity.java
- src/main/java/com/sparta/levelup_backend/domain/product/repository/ProductRepository.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
Delete annotation
Delete variable settings
Change is_deleted-based data
Clear CRUD Error
> fix: CRUD fix

- src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
- src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
- src/main/java/com/sparta/levelup_backend/utill/JwtUtils.java
- 이미 발급된 로그인 토큰에 대해서 삭제여부 검증 및 권한정보, id정보 가져오는 부분 삭제
- 토큰에 권한정보와 id정보를 넣어두고 꺼내오도록 변경
> Fix: add token role,id

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/common/entity/BaseEntity.java
- src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/FindGameRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/UpdateGameRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/game/entity/GameEntity.java
- src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
- src/main/java/com/sparta/levelup_backend/domain/game/repsitory/GameRepository.java
- src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
- src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- src/main/java/com/sparta/levelup_backend/exception/common/ForbiddenException.java
game crud작업했습니다.
아직 valid작업은 안되어있는 상태입니다.
저도 다시 생각할테지만 가볍게 보시면서 서비스 레이어에서 예외처리가 더 필요한 부분이 있을때 알려주시면 감사하겠습니다.
> feat: Game CRUD

- src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/requestDto/CreateGameRequestDto.java
불필요한 주석 제거
CreateGameRequestDto 변수 이름 수정
> fix: delete comment

- build.gradle
- src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
- src/main/java/com/sparta/levelup_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/sparta/levelup_backend/domain/review/entity/ReviewEntity.java
- src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
- src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewRepository.java
- src/main/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/DuplicateException.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- src/test/java/com/sparta/levelup_backend/domain/review/service/ReviewServiceImplTest.java
- 주문 테이블과 연관관계 설정
- 거래완료한 사용자인지 검증 로직 추가
- 이미 리뷰를 작성한 사용자인지 검증 로직 추가
- 이미 삭제된 리뷰인지 검증 로직 추가
- 삭제된 리뷰 목록 조회에서 제외되도록 수정
- 추가된 검증에 대한 테스트코드 작성
> feat: review refactor

- src/main/java/com/sparta/levelup_backend/domain/game/repository/GameRepository.java
- src/main/java/com/sparta/levelup_backend/domain/product/controller/ProductController.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/ValidMessage.java
- src/main/java/com/sparta/levelup_backend/domain/product/dto/responseDto/ProductDeleteResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductService.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/product/service/ProductmakedataService.java
> fix: Product CRUD Update And Error Clear

- src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
- src/main/java/com/sparta/levelup_backend/config/CustomUsernamePasswordAuthenticationFilter.java
- src/main/java/com/sparta/levelup_backend/config/JwtFilter.java
- src/main/java/com/sparta/levelup_backend/config/SecurityConfig.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- 오류가 포스트맨으로 표시 안되는 문제를 해결했습니다.
> fix: exception not showing

- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
> fix : orderRefactor

- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
주문생성 기능 버그 수정
비활성화 및 소프트 딜리트가 된 상품 
주문이 가능하던 버그 수정
> feat: OrderFix

- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImpl.java
> Fix : OrderFix

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/config/CustomAccessDeniedHandler.java
- src/main/java/com/sparta/levelup_backend/domain/auth/dto/request/SignUpUserRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/user/dto/UserValidMessage.java
- src/main/java/com/sparta/levelup_backend/domain/user/dto/request/ChangePasswordDto.java
- src/main/java/com/sparta/levelup_backend/domain/user/dto/request/DeleteUserRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/user/dto/request/UpdateUserRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/user/service/UserServiceImpl.java
- 이메일, 전화번호 유효성 검사 추가
- userRepository Impl 부분 삭제
> fix: fix valid and repository impl

- src/main/java/com/sparta/levelup_backend/domain/review/dto/response/ReviewResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/review/repository/ReviewQueryRepository.java
- 리뷰 목록 조회에 닉네임 추가
- 리뷰 목록 조회에 productId 제거
> fix: reviews find nickname / productId remove

- src/main/java/com/sparta/levelup_backend/domain/game/controller/GameController.java
- src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/game/service/GameService.java
- src/main/java/com/sparta/levelup_backend/domain/game/service/GameServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- change userRespository.findById in GameServiceImpl
- 삭제된 상황에서 다시 삭제를 시도할때 예외 발생
- 삭제된 게임을 조회할때 예외 발생
- RUD api에 권한 검사 추가
- 게임 목록 조회
> fix: Game while merge to develop

- src/main/java/com/sparta/levelup_backend/domain/game/dto/responseDto/GameListResponseDto.java
응답시 gameListResponseDto로 표기되던 문제를 gameList로 변경
> fix: Change Dto Response Name

- src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
- src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
- src/main/java/com/sparta/levelup_backend/domain/bill/service/BillService.java
- src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/order/controller/OrderControllerV2.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceV2.java
- src/main/java/com/sparta/levelup_backend/utill/BillStatus.java
결제내역서 생성 구현
- Sevice층에 메소드만 구현하여 정책상 order의 상태가 거래중으로 바뀔때 생성되어야해서 메소드 적용 시켰습니다.
> feat : bill create

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/bill/controller/BillControllerV2.java
- src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
- src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceImplV2.java
- src/main/java/com/sparta/levelup_backend/domain/bill/service/BillServiceV2.java
결제내역 삭제 기능
- tutor 전용
- student 전용
> feat : orderBillDelete

- src/main/java/com/sparta/levelup_backend/domain/bill/entity/BillEntity.java
- src/main/java/com/sparta/levelup_backend/domain/bill/repository/BillRepository.java
- src/main/java/com/sparta/levelup_backend/domain/order/service/OrderServiceImplV2.java
결제 취소 기능 구현
- 이미 결제가 이루어진 주문이 거래중인 상태일때 취소하는 API에 bill상태 Cancle로 변경 로직 추가
> feat : orderBillCancle

- build.gradle
- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/config/MongoDBConfig.java
- src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
- src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
- src/main/java/com/sparta/levelup_backend/domain/chat/entity/ChatMessage.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatService.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/sparta/levelup_backend/ui/PageController.java
- src/main/resources/static/css/common.css
- src/main/resources/templates/chatroom.html
- src/main/resources/templates/login.html
- MongoDB 연결 추가
- 메시지 기록 MongoDB로 저장되도록 변경
> feat: chat refactor

- src/main/java/com/sparta/levelup_backend/common/ApiResMessage.java
- src/main/java/com/sparta/levelup_backend/domain/community/controller/CommunityController.java
- src/main/java/com/sparta/levelup_backend/domain/community/dto/CommunityValidMessage.java
- src/main/java/com/sparta/levelup_backend/domain/community/dto/request/CommunityUpdateRequestDto.java
- src/main/java/com/sparta/levelup_backend/domain/community/dto/response/CommunityResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/community/entity/CommunityEntity.java
- src/main/java/com/sparta/levelup_backend/domain/community/repository/CommunityRepository.java
- src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityService.java
- src/main/java/com/sparta/levelup_backend/domain/community/service/CommunityServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
> feat: Update Community Api

- build.gradle
- src/main/java/com/sparta/levelup_backend/config/RedisChatConfig.java
- src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
- src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisPublisher.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/RedisSubscriber.java
- src/main/resources/static/css/common.css
- src/main/resources/templates/chatroom.html
- 실시간 채팅시 Redis Pub/Sub 으로 주고받도록 변경
> recfactor: chat refactor

- src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
- src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatroomController.java
- src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
- src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatroomDocument.java
- src/main/java/com/sparta/levelup_backend/domain/chat/document/Participant.java
- src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomCreateResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatroomListResponseDto.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomQueryRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
- src/main/java/com/sparta/levelup_backend/exception/common/BadRequestException.java
- src/main/java/com/sparta/levelup_backend/exception/common/ErrorCode.java
- src/main/java/com/sparta/levelup_backend/proto/JwtAuthenticationSuccessHandler.java
- 기존 MySQL 사용하던 채팅방 테이블을 MongoDB 도큐먼트를 사용하도록 변경
- 채팅방 관련 API 서비스 로직 변경
> recfactor: chatroom MySQL -> MongoDB

- src/main/java/com/sparta/levelup_backend/domain/chat/controller/ChatController.java
- src/main/java/com/sparta/levelup_backend/domain/chat/document/ChatMessage.java
- src/main/java/com/sparta/levelup_backend/domain/chat/dto/ChatMessageDto.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatMongoRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/repository/ChatroomMongoRepository.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatService.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomService.java
- src/main/java/com/sparta/levelup_backend/domain/chat/service/ChatroomServiceImpl.java
- src/main/java/com/sparta/levelup_backend/ui/PageController.java
- src/main/resources/templates/chatroomList.html
- src/main/resources/templates/productDetail.html
- 채팅 안 읽은 메시지 수, 마지막 메시지 업데이트 기능 추가
> feat: Chatrooms UnreadMessages/LastMessage Update

- src/main/resources/templates/signin.html
- 로그인페이지 진입할때 리프레시 토큰을 지우고 시작하도록 변경.
> fix: Delete Token
